### ISSUE TITLE
GNU11 argument checking

### ISSUE THREAD

**Issue by LucasVisscher** [ORNL-QCI/ExaTENSOR#2]
With the latest GNU compilers building fails with 

```
Error: Type mismatch between actual argument at (1) and actual argument at (2) (COMPLEX(8)/REAL(4)).
```

This compiler bug is easily circumvented by adding -fallow-argument-mismatch to the GNU options in the Makefiles inside INTRAVIRT and INTERVIRT. Not being able to do so via an environment variable is, however, currently blocking DIRAC tests as cmake downloads a fresh copy of exatensor every time it builds.

**Comment by DmitryLyakh** [comment]
Fixed.
